version: '3'

services:
  db:
    container_name: mysql_tech_test
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: renas
      MYSQL_PASSWORD: ustek
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - './docker/db/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql'

